#!/bin/bash
set -e

# do pre-commit hooks run in the repository root always?

if
    git diff --cached | egrep '^\+.*	'>/dev/null
then
    echo "Tabs found in your commit. Please use (four) spaces and re-commit."
    exit 1
fi

s/build || exit 1
s/runtests || exit 1
