#!/bin/bash
set -e

if [ "" != "$GIT_DIR" ]; then
    cd "$GIT_DIR"/..
else
    cd "`dirname \"$0\"`"/..
fi

if
    git diff --cached | egrep '^\+.*	'>/dev/null
then
    echo "Tabs found in your commit. Please use (four) spaces and re-commit."
    exit 1
fi

s/build || exit 1
s/runtests || exit 1
