#!/bin/bash

HERE=`dirname "$0"`/..

set -e

function relpath() {
    python "$HERE/bin/relpath.py" "$@"
}

function normpath() {
    realpath "$@"
}

if [ "$1" ]; then
    REPOSITORY_ROOT="$1"
else
    REPOSITORY_ROOT="$HERE"
fi

DOTGIT="$REPOSITORY_ROOT/.git"

if [ -f "$DOTGIT" ]; then
    if [ x"$REPOSITORY_ROOT" = x"." ]; then
	PREFIX=
    else
	PREFIX=$REPOSITORY_ROOT/
    fi
    GITDIR=$PREFIX`cat "$DOTGIT" | sed "s/gitdir: //"`
elif [ -d "$DOTGIT" ]; then
    GITDIR="$DOTGIT"
else
    echo "Could not find .git directory.  Is '$REPOSITORY_ROOT' a git repository?"
    exit 1
fi

GITHOOKDIR="$GITDIR/hooks"
MYHOOKS="$REPOSITORY_ROOT/githooks"
MYHOOKSLINK=$(relpath "$MYHOOKS" "$GITHOOKDIR")

GITHOOKDIR=$(normpath "$GITHOOKDIR")

for hook in $(cd $MYHOOKS && ls); do
    target="$GITHOOKDIR/$hook"
    rm -f $target
    echo "#/bin/bash" > $target
    echo "HERE=\`dirname \"\$0\"\`" >> $target
    echo "exec \"\$HERE/$MYHOOKSLINK/$hook\"" >> $target
    chmod +x $target
done
