#!/bin/bash

HERE=`dirname "$0"`/..

set -e

# TODO: take an argument for repository root
REPOSITORY_ROOT="$HERE"
DOTGIT="$HERE/.git"

if [ -f "$REPOSITORY_ROOT/.git" ]; then
    GITDIR=$REPOSITORY_ROOT/`cat "$REPOSITORY_ROOT/.git" | sed "s/gitdir: //"`
else
    GITDIR="$REPOSITORY_ROOT/.git"
fi

for hook in $REPOSITORY_ROOT/githooks/*; do
    ln -f $hook "$GITDIR/hooks"
done
