#!/bin/bash

HERE=`dirname "$0"`/..

set -e

# TODO: take an argument for repository root
REPOSITORY_ROOT="$HERE"
DOTGIT="$REPOSITORY_ROOT/.git"

if [ -f "$DOTGIT" ]; then
    GITDIR=$REPOSITORY_ROOT/`cat "$DOTGIT" | sed "s/gitdir: //"`
else
    GITDIR="$DOTGIT"
fi

for hook in $REPOSITORY_ROOT/githooks/*; do
    ln -f $hook "$GITDIR/hooks"
done
