#!/bin/bash
cd `dirname "$0"`/..

set -e

function error_exit() {
    set +x
    echo "Error, aborting..."
    exit 1
}
trap error_exit ERR

set -x
git submodule sync
git submodule update --init --recursive
